export const data = [
	{
		"walk_minutes_per_day": 35,
		"enjoys_walking": false,
		"checkins_total": 7,
		"steps_total": 51000,
		"steps_daily_avg": 2500,
		"steps_best_day": 3500,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 25,
		"enjoys_walking": true,
		"checkins_total": 6,
		"steps_total": 16820,
		"steps_daily_avg": 1520,
		"steps_best_day": 1610,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 2038,
		"steps_daily_avg": 2038,
		"steps_best_day": 2038,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 2054,
		"steps_daily_avg": 2054,
		"steps_best_day": 2054,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 2087,
		"steps_daily_avg": 2087,
		"steps_best_day": 2087,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 46,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 5876,
		"steps_daily_avg": 1959,
		"steps_best_day": 5760,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 33,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 332,
		"steps_daily_avg": 83,
		"steps_best_day": 234,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 45,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 795,
		"steps_daily_avg": 398,
		"steps_best_day": 752,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 30,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 350,
		"steps_daily_avg": 350,
		"steps_best_day": 350,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 30,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 6811,
		"steps_daily_avg": 1703,
		"steps_best_day": 2161,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 20,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 175,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 179,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 110,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 193,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 11436,
		"steps_daily_avg": 1040,
		"steps_best_day": 3759,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 784,
		"steps_daily_avg": 784,
		"steps_best_day": 784,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 1220,
		"steps_daily_avg": 1220,
		"steps_best_day": 1220,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 15,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 1503,
		"steps_daily_avg": 1503,
		"steps_best_day": 1503,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 37,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 977,
		"steps_daily_avg": 488,
		"steps_best_day": 877,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 7,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 7996,
		"steps_daily_avg": 3998,
		"steps_best_day": 6258,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 10,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 8003,
		"steps_daily_avg": 8003,
		"steps_best_day": 8003,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 87,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 8003,
		"steps_daily_avg": 8003,
		"steps_best_day": 8003,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 61,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 494,
		"steps_daily_avg": 494,
		"steps_best_day": 494,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 34,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 10,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 35499,
		"steps_daily_avg": 11833,
		"steps_best_day": 21192,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 330,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 125566,
		"steps_daily_avg": 125566,
		"steps_best_day": 125566,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 160,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 125590,
		"steps_daily_avg": 125590,
		"steps_best_day": 125590,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 720,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 125590,
		"steps_daily_avg": 125590,
		"steps_best_day": 125590,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 301,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 242,
		"steps_daily_avg": 242,
		"steps_best_day": 242,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 60,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 21263,
		"steps_daily_avg": 21263,
		"steps_best_day": 21263,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 15,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 23203,
		"steps_daily_avg": 23203,
		"steps_best_day": 23203,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 45,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 23203,
		"steps_daily_avg": 23203,
		"steps_best_day": 23203,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 50,
		"enjoys_walking": false,
		"checkins_total": 1,
		"steps_total": 35761,
		"steps_daily_avg": 11920,
		"steps_best_day": 34717,
		"playertype": 1,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 20
	},
	{
		"walk_minutes_per_day": 175,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 86,
		"steps_daily_avg": 86,
		"steps_best_day": 86,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": false,
		"checkins_total": 2,
		"steps_total": 4260,
		"steps_daily_avg": 4260,
		"steps_best_day": 4260,
		"playertype": 1,
		"step_goal_1_reached": 1,
		"step_goal_2_reached": 1,
		"step_goal_3_reached": 1,
		"app_starts": 20
	},
	{
		"walk_minutes_per_day": 30,
		"enjoys_walking": false,
		"checkins_total": 1,
		"steps_total": 47,
		"steps_daily_avg": 47,
		"steps_best_day": 47,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 19,
		"enjoys_walking": false,
		"checkins_total": 1,
		"steps_total": 47,
		"steps_daily_avg": 47,
		"steps_best_day": 47,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 34,
		"enjoys_walking": false,
		"checkins_total": 1,
		"steps_total": 17276,
		"steps_daily_avg": 1571,
		"steps_best_day": 2073,
		"playertype": 3,
		"step_goal_1_reached": 1,
		"step_goal_2_reached": 1,
		"step_goal_3_reached": 1,
		"app_starts": 46
	},
	{
		"walk_minutes_per_day": 27,
		"enjoys_walking": false,
		"checkins_total": 1,
		"steps_total": 552,
		"steps_daily_avg": 552,
		"steps_best_day": 552,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 3
	},
	{
		"walk_minutes_per_day": 16,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 536,
		"steps_daily_avg": 536,
		"steps_best_day": 536,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 7
	},
	{
		"walk_minutes_per_day": 61,
		"enjoys_walking": false,
		"checkins_total": 2,
		"steps_total": 2253,
		"steps_daily_avg": 751,
		"steps_best_day": 1024,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 7
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": true,
		"checkins_total": 6,
		"steps_total": 1522,
		"steps_daily_avg": 2480,
		"steps_best_day": 3100,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 0,
		"enjoys_walking": true,
		"checkins_total": 6,
		"steps_total": 1522,
		"steps_daily_avg": 2480,
		"steps_best_day": 3100,
		"playertype": null,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 0
	},
	{
		"walk_minutes_per_day": 10,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 852,
		"steps_daily_avg": 852,
		"steps_best_day": 852,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 17
	},
	{
		"walk_minutes_per_day": 48,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 592,
		"steps_daily_avg": 592,
		"steps_best_day": 592,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 16,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 493,
		"steps_daily_avg": 493,
		"steps_best_day": 493,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 16,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 368,
		"steps_daily_avg": 368,
		"steps_best_day": 368,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 13,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 435,
		"steps_daily_avg": 435,
		"steps_best_day": 435,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 8
	},
	{
		"walk_minutes_per_day": 13,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 554,
		"steps_daily_avg": 554,
		"steps_best_day": 554,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 61,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 418,
		"steps_daily_avg": 418,
		"steps_best_day": 418,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 10,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 3528,
		"steps_daily_avg": 441,
		"steps_best_day": 708,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 49
	},
	{
		"walk_minutes_per_day": 198,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 241163,
		"steps_daily_avg": 60291,
		"steps_best_day": 107199,
		"playertype": 3,
		"step_goal_1_reached": 3,
		"step_goal_2_reached": 3,
		"step_goal_3_reached": 3,
		"app_starts": 9
	},
	{
		"walk_minutes_per_day": 99,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 5084,
		"steps_daily_avg": 1271,
		"steps_best_day": 2584,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 9
	},
	{
		"walk_minutes_per_day": 60,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 226278,
		"steps_daily_avg": 32325,
		"steps_best_day": 0,
		"playertype": 3,
		"step_goal_1_reached": 3,
		"step_goal_2_reached": 2,
		"step_goal_3_reached": 2,
		"app_starts": 7
	},
	{
		"walk_minutes_per_day": 180,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 9540,
		"steps_daily_avg": 3180,
		"steps_best_day": 9523,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 7
	},
	{
		"walk_minutes_per_day": 30,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 10179,
		"steps_daily_avg": 2036,
		"steps_best_day": 7634,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 5
	},
	{
		"walk_minutes_per_day": 35,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 620720,
		"steps_daily_avg": 47748,
		"steps_best_day": 132608,
		"playertype": 3,
		"step_goal_1_reached": 3,
		"step_goal_2_reached": 3,
		"step_goal_3_reached": 3,
		"app_starts": 20
	},
	{
		"walk_minutes_per_day": 116,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 121054,
		"steps_daily_avg": 9312,
		"steps_best_day": 34789,
		"playertype": 3,
		"step_goal_1_reached": 2,
		"step_goal_2_reached": 2,
		"step_goal_3_reached": 2,
		"app_starts": 29
	},
	{
		"walk_minutes_per_day": 180,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 3229,
		"steps_daily_avg": 1614,
		"steps_best_day": 2616,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 60,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 60,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 643,
		"steps_daily_avg": 161,
		"steps_best_day": 409,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 9
	},
	{
		"walk_minutes_per_day": 120,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 71751,
		"steps_daily_avg": 4221,
		"steps_best_day": 68,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 11
	},
	{
		"walk_minutes_per_day": 100,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 12415,
		"steps_daily_avg": 12415,
		"steps_best_day": 12415,
		"playertype": 3,
		"step_goal_1_reached": 1,
		"step_goal_2_reached": 1,
		"step_goal_3_reached": 1,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 59,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 309,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 107199,
		"steps_daily_avg": 107199,
		"steps_best_day": 107199,
		"playertype": 3,
		"step_goal_1_reached": 1,
		"step_goal_2_reached": 1,
		"step_goal_3_reached": 1,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 66,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 335,
		"steps_daily_avg": 335,
		"steps_best_day": 335,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 128,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 122,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 48,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 3
	},
	{
		"walk_minutes_per_day": 44,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 3712,
		"steps_daily_avg": 1856,
		"steps_best_day": 3711,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 425,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 377,
		"steps_daily_avg": 188,
		"steps_best_day": 469,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 70,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 190,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 531,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 12
	},
	{
		"walk_minutes_per_day": 170,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 14110,
		"steps_daily_avg": 1764,
		"steps_best_day": 3876,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 36
	},
	{
		"walk_minutes_per_day": 45,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 522,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 15,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 763,
		"steps_daily_avg": 382,
		"steps_best_day": 585,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 7
	},
	{
		"walk_minutes_per_day": 30,
		"enjoys_walking": true,
		"checkins_total": 4,
		"steps_total": 1219,
		"steps_daily_avg": 305,
		"steps_best_day": 640,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 34
	},
	{
		"walk_minutes_per_day": 32,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 243,
		"steps_daily_avg": 122,
		"steps_best_day": 243,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 9
	},
	{
		"walk_minutes_per_day": 160,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 1045,
		"steps_daily_avg": 522,
		"steps_best_day": 701,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 2
	},
	{
		"walk_minutes_per_day": 45,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 790,
		"steps_daily_avg": 395,
		"steps_best_day": 446,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 30,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 915,
		"steps_daily_avg": 458,
		"steps_best_day": 571,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 60,
		"enjoys_walking": false,
		"checkins_total": 0,
		"steps_total": 971,
		"steps_daily_avg": 486,
		"steps_best_day": 627,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 25,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 971,
		"steps_daily_avg": 486,
		"steps_best_day": 627,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 35,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 971,
		"steps_daily_avg": 486,
		"steps_best_day": 627,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 55,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 971,
		"steps_daily_avg": 486,
		"steps_best_day": 627,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 25,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 679,
		"steps_daily_avg": 679,
		"steps_best_day": 679,
		"playertype": 2,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 35,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 3087,
		"steps_daily_avg": 617,
		"steps_best_day": 830,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 3
	},
	{
		"walk_minutes_per_day": 130,
		"enjoys_walking": true,
		"checkins_total": 3,
		"steps_total": 42,
		"steps_daily_avg": 42,
		"steps_best_day": 42,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 3
	},
	{
		"walk_minutes_per_day": 150,
		"enjoys_walking": true,
		"checkins_total": 1,
		"steps_total": 1713,
		"steps_daily_avg": 1713,
		"steps_best_day": 1713,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 4
	},
	{
		"walk_minutes_per_day": 125,
		"enjoys_walking": true,
		"checkins_total": 3,
		"steps_total": 891,
		"steps_daily_avg": 446,
		"steps_best_day": 731,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 37
	},
	{
		"walk_minutes_per_day": 130,
		"enjoys_walking": true,
		"checkins_total": 2,
		"steps_total": 3716,
		"steps_daily_avg": 743,
		"steps_best_day": 2324,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 14
	},
	{
		"walk_minutes_per_day": 45,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 21689,
		"steps_daily_avg": 2410,
		"steps_best_day": 6616,
		"playertype": 3,
		"step_goal_1_reached": 3,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 34
	},
	{
		"walk_minutes_per_day": 110,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 3223,
		"steps_daily_avg": 1612,
		"steps_best_day": 2540,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 3
	},
	{
		"walk_minutes_per_day": 70,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 19979,
		"steps_daily_avg": 6660,
		"steps_best_day": 11915,
		"playertype": 3,
		"step_goal_1_reached": 2,
		"step_goal_2_reached": 2,
		"step_goal_3_reached": 1,
		"app_starts": 6
	},
	{
		"walk_minutes_per_day": 100,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 300,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 5085,
		"steps_daily_avg": 1017,
		"steps_best_day": 2886,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 4
	},
	{
		"walk_minutes_per_day": 300,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 2846,
		"steps_daily_avg": 2846,
		"steps_best_day": 2846,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 1
	},
	{
		"walk_minutes_per_day": 45,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 0,
		"steps_daily_avg": 0,
		"steps_best_day": 0,
		"playertype": 3,
		"step_goal_1_reached": 0,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 33
	},
	{
		"walk_minutes_per_day": 30,
		"enjoys_walking": true,
		"checkins_total": 0,
		"steps_total": 3733,
		"steps_daily_avg": 3733,
		"steps_best_day": 3733,
		"playertype": 3,
		"step_goal_1_reached": 1,
		"step_goal_2_reached": 0,
		"step_goal_3_reached": 0,
		"app_starts": 4
	}
];